### ISSUE TITLE
Next.js `12.1.6` で Jest のテストが失敗する

### ISSUE THREAD

**Issue by gh640** [gh640/nextjs-blog-example-ja#110]
Next.js `12.1.5` から `12.1.6` にあげると `next/link` をモックした Jest のテストが失敗するようになりました。

- https://github.com/gh640/nextjs-blog-example-ja/pull/107/checks

サンプル:

```text
FAIL __tests__/index.test.js
  ● Test suite failed to run

    TypeError: _link.default.mockImplementation is not a function

      10 |
      11 | describe("Home", () => {
    > 12 | 	Link.mockImplementation(({ href, children }) => 
         | 	     ^
      13 | 		cloneElement(children, { href })
      14 | 	)
      15 | 	Layout.mockImplementation(({ children }) => children)

      at __tests__/index.test.js:12:7
      at Object.<anonymous> (__tests__/index.test.js:11:1)
```

**Comment by gh640** [comment]
`mockImplementation()` をやめて `jest.mock` で同様の設定するようにすると解消しました:

```js
jest.mock("next/link", () => {
	return ({ children, ...attrs }) => {
		return <a {...attrs}>{children}</a>
	}
})
```
