### ISSUE TITLE
`npm run build` でエラー `ReferenceError: jest is not defined` が発生する

### ISSUE THREAD

**Issue by gh640** [gh640/nextjs-blog-example-ja#22]
```bash
$ npm run build

> nextjs-blog-example-ja@0.1.1 build
> next build

info  - Loaded env from /path/to/nextjs-blog-example-ja/.env.local
info  - Using webpack 5. Reason: no next.config.js https://nextjs.org/docs/messages/webpack5
info  - Checking validity of types  
info  - Using external babel configuration from /path/to/nextjs-blog-example-ja/babel.config.js
info  - Creating an optimized production build  
info  - Compiled successfully

> Build error occurred
ReferenceError: jest is not defined
    at Object.6864 (/path/to/nextjs-blog-example-ja/.next/server/pages/__tests__/index.test.js:2921:1)
    at __webpack_require__ (/path/to/nextjs-blog-example-ja/.next/server/webpack-runtime.js:25:42)
    at __webpack_exec__ (/path/to/nextjs-blog-example-ja/.next/server/pages/__tests__/index.test.js:3142:52)
    at /path/to/nextjs-blog-example-ja/.next/server/pages/__tests__/index.test.js:3143:28
    at Object.<anonymous> (/path/to/nextjs-blog-example-ja/.next/server/pages/__tests__/index.test.js:3146:3)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Module.require (node:internal/modules/cjs/loader:999:19) {
  type: 'ReferenceError'
}
info  - Collecting page data .
```

**Comment by gh640** [comment]
問題の原因は `pages` 内のページを生成するための React コンポーネントのテストを同じ `pages/` ディレクトリに置いてしまっていたことでした。

`__tests__` を `pages/` の外に移動することで解決しました。

該当コミット: https://github.com/gh640/nextjs-blog-example-ja/commit/99fa15acd35312cade6925c95fac098c0cdd5317
