### ISSUE TITLE
Node.js v17.x で `ERR_OSSL_EVP_UNSUPPORTED` エラー

### ISSUE THREAD

**Issue by gh640** [gh640/nextjs-blog-example-ja#49]
Node.js v17.0.1 で `npm run dev` や `npm run build` を実行すると `ERR_OSSL_EVP_UNSUPPORTED` のエラーが出ます。

```text
❯ npm run dev

> nextjs-blog-example-ja@0.1.1 dev
> next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from /project_root/.env.local
info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at BulkUpdateDecorator.hashFactory (/project_root/node_modules/next/dist/compiled/webpack/bundle5.js:138971:18)
    at BulkUpdateDecorator.digest (/project_root/node_modules/next/dist/compiled/webpack/bundle5.js:138906:21)
    at getHash (/project_root/node_modules/next/dist/compiled/webpack/bundle5.js:101615:45)
    at getLongModuleName (/project_root/node_modules/next/dist/compiled/webpack/bundle5.js:101695:25)
    at /project_root/node_modules/next/dist/compiled/webpack/bundle5.js:102180:24
    at assignNames (/project_root/node_modules/next/dist/compiled/webpack/bundle5.js:101894:22)
    at /project_root/node_modules/next/dist/compiled/webpack/bundle5.js:102173:28
    at Hook.eval [as call] (eval at create (/project_root/node_modules/next/dist/compiled/webpack/bundle5.js:33818:10), <anonymous>:7:1) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.0.1
```

**Comment by gh640** [comment]
Node.js v17 で OpenSSL 3.0 を含む形に変わったことに起因するようです。 v17 のリリースノートに次のように書かれています。

> OpenSSL 3.0
> 
> （中略）
> 
> If you hit an `ERR_OSSL_EVP_UNSUPPORTED` error in your application with Node.js 17, it’s likely that your application or a module you’re using is attempting to use an algorithm or key size which is no longer allowed by default with OpenSSL 3.0. A command-line option, `--openssl-legacy-provider`, has been added to revert to the legacy provider as a temporary workaround for these tightened restrictions.

https://nodejs.org/en/blog/release/v17.0.0/#openssl-3-0

とのことなので、一時的な対応としては `NODE_OPTIONS=--openssl-legacy-provider` をつけて実行するようにすると OK です。

```bash
# 開発環境
NODE_OPTIONS=--openssl-legacy-provider npm run dev

# ビルド
NODE_OPTIONS=--openssl-legacy-provider npm run build
```

関連イシュー・質問:

- https://github.com/webpack/webpack/issues/14532
- https://stackoverflow.com/questions/69665222/node-17-0-1-causes-some-error-digital-envelope-routinesunsupported

**Comment by gh640** [comment]
#173 で Node 18 にあげましたが、特に問題は起こりませんでした。

- #173

本イシューは閉じます。
